title: IlWon Blog
description: Developer

url: https://ilwon126.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: ilwon126
   twitter: arsia12
   facebook: ilwon.seo.7
   email: arsia12@gmail.com

google_analytics: "UA-131509751-1"
